/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jawlex (https://sketchfab.com/jawlex3d)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-banana-fa66af3e1e2d43328f34110945bfb672
Title: Low-Poly Banana
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Banana = (props) => {
  const { nodes, materials } = useGLTF('/models/low_poly_banana.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.8}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Banana_PM3D_Cylinder3D_1_2_0.geometry}
          material={materials.PM3D_Cylinder3D_1_2}
          rotation={[0, Math.PI / 2, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_banana.glb')

export default Banana