/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: irisshrestha (https://sketchfab.com/irisshrestha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/king-black-dragon-5991a166b85f4c49b5e827227ee2858e
Title: King black dragon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HeroModel = (props) => {
  const { nodes, materials } = useGLTF('/models/scene.glb')
//  const { nodes, materials } = useGLTF('/models/scene.gltf')
//  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.012, 0.02, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[152.795, 9.657, -1.668]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[15.15, 20.219, 15.15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head_top_Black_0.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head_Bottom_Black_0.geometry}
              material={materials.Black}
              position={[-0.673, 0, -1.698]}
              scale={0.717}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.All_Teeth_Black_0.geometry}
              material={materials.Black}
              position={[3.075, 0.186, -3.471]}
              rotation={[-0.11, 0.623, 3.123]}
              scale={[-0.105, 0.079, 0.175]}
            />
          </group>
          <group
            position={[138.642, 6.642, -78.794]}
            rotation={[-1.546, 0.014, 0.521]}
            scale={[15.15, 20.219, 15.15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head_top001_Black_0.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head_Bottom001_Black003_0.geometry}
              material={materials['Black.003']}
              position={[-0.673, 0, -1.698]}
              scale={0.717}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.All_Teeth001_Black_0.geometry}
              material={materials.Black}
              position={[3.075, 0.186, -3.471]}
              rotation={[-0.11, 0.623, 3.123]}
              scale={[-0.105, 0.079, 0.175]}
            />
          </group>
          <group
            position={[150.259, 6.809, 64.939]}
            rotation={[-1.544, -0.008, -0.299]}
            scale={[15.15, 20.219, 15.15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head_top002_Black_0.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head_Bottom002_Black_0.geometry}
              material={materials.Black}
              position={[-0.673, 0, -1.698]}
              scale={0.717}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.All_Teeth002_Black_0.geometry}
              material={materials.Black}
              position={[3.075, 0.186, -3.471]}
              rotation={[-0.11, 0.623, 3.123]}
              scale={[-0.105, 0.079, 0.175]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dragon_Body_Black001_0.geometry}
            material={materials['Black.001']}
            position={[-45.576, 1.139, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={31.287}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wing_Black002_0.geometry}
            material={materials['Black.002']}
            position={[16.165, -1.179, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[11.633, 27.256, 8.717]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Claws_Black_0.geometry}
            material={materials.Black}
            position={[-152.96, -142.563, -57.397]}
            rotation={[-1.571, 1.552, 3.142]}
            scale={[-3.383, 1.916, 3.189]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/scene.glb')
//useGLTF.preload('/models/scene.gltf')
//useGLTF.preload('/scene.gltf')

export default HeroModel;
