/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gman08 (https://sketchfab.com/Gman08)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubix-cube-8c9a5d13325b4923baac1bf038a01913
Title: Rubix Cube
*/

import { useRef, useState } from 'react'
import { useGLTF, Float } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const RubixCube = (props) => {
  const { nodes, materials } = useGLTF('/models/rubix_cube.glb')
  const cubeRef = useRef();
  const [hovered, setHovered] = useState(false);

  useGSAP(()=> {
    gsap
      .timeline({
        repeat: -1,
        repeatDelay: 0.5,
      })
      .to(cubeRef.current.rotation, {
        x: hovered ? '+=2' : `+=${Math.PI * 2}`,
        y: hovered ? '+=2' : `+=${Math.PI * 2}`,
        duration: 15,
        stagger: {
          each: 0.15,
        }
      })
  })

  return (
    <Float floatIntensity={2}>
      <group 
        ref={cubeRef} 
        onPointerEnter={() => setHovered(true)} 
        scale={0.002} {...props} dispose={null}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials['Material.007']}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/rubix_cube.glb')

export default RubixCube